doc: first version of the software version proposal
atomone-hub/govgen-proposals pull request #26
Opened 2024-08-14 16:41 UTC by tbruyelle

2024-08-28 16:45 UTC, jaekwon approved these changes

2024-09-04 14:22 UTC, giunatale requested changes

2024-09-04 14:22 UTC, giunatale commented on 002_SOFTWARE_VERSIONING.md
> +On the other hand, v0.50 brings some interesting features in term of
```suggestion
On the other hand, while v0.50 brings some interesting features in term of
```

2024-09-04 14:22 UTC, giunatale commented on 002_SOFTWARE_VERSIONING.md
> +modularity, but it's not used by the CosmosHub yet (at the time of writing,
```suggestion
modularity, it is not used by the CosmosHub yet (at the time of writing,
```

2024-09-04 14:22 UTC, giunatale commented on 002_SOFTWARE_VERSIONING.md
> +Gaia v19 upgrade proposal is still in voting period).
Is this the only argument we want to bring for discarding 0.50.x? Might be challenged if put it this way. I think we need to put emphasis on the fact that newer versions have less guarantees in terms of reliability. Unless this was already discussed or decided to not mention, imho it should be.

2024-09-04 14:22 UTC, giunatale commented on 002_SOFTWARE_VERSIONING.md
> +Obviously, v18 is discarded because AtomOne won't have any VM functionality, as
```suggestion
AtomOne will not have any VM functionality as
```

2024-09-04 14:22 UTC, giunatale commented on 002_SOFTWARE_VERSIONING.md
> +specified in the draft of the [Constitution].
```suggestion
specified in the draft of the [Constitution], thus v18 gets automatically discarded.
```

2024-09-04 14:22 UTC, giunatale commented on 002_SOFTWARE_VERSIONING.md
> +Then, considering that the first version of AtomOne won't have IBC or ICS
```suggestion
Considering that the first version of AtomOne will not have IBC or ICS
```

2024-09-04 14:22 UTC, giunatale commented on 002_SOFTWARE_VERSIONING.md
> +enabled, there's no advantage in choosing to fork v16 or v17.
```suggestion
enabled, there is no advantage in choosing to fork v16 or v17.
```

2024-09-04 14:22 UTC, giunatale commented on 002_SOFTWARE_VERSIONING.md
> +This left out v15, which is the version we propose to fork for AtomOne.
```suggestion
This leaves out only v15, which is the version we propose to fork for AtomOne.
```

2024-09-04 14:34 UTC, tbruyelle commented on 002_SOFTWARE_VERSIONING.md
> +Gaia v19 upgrade proposal is still in voting period).
This is a good point, let's improve that part.

2024-09-05 11:26 UTC, tbruyelle commented on 002_SOFTWARE_VERSIONING.md
> +Gaia v19 upgrade proposal is still in voting period).
@giunatale see aaa72667fb714518227a21776461fb6044e48342

2024-09-06 15:49 UTC, giunatale approved these changes

2024-09-06 16:35 UTC, merged