doc: proposal template & instructions
atomone-hub/govgen-proposals pull request #3
Opened 2024-02-28 14:35 UTC by tbruyelle

This PR contains a suggestion for a proposal template that can be used to create new proposal in the repo.
Also adds instructions in the README.

2024-02-29 17:06 UTC, tbruyelle commented on XXX_proposal_template.md
> +[Draft|Abandonned|Deposit|Voting]
Maybe should be just have `[Draft|Abandonned|On Chain]`, so we don't have to update it once it's on chain, we can just forget it.

2024-03-04 09:43 UTC, tbruyelle commented
> @tbruyelle Should we add different types of proposals they can submit or not needed? I suppose this could be added to the proposal ID? (E.g. signaling, parameter change, community, software upgrade, etc.)

Good point, the template aims only text proposals for AtomOne, I'm going to add this information.

2024-03-05 16:43 UTC, giunatale approved these changes

2024-03-05 16:43 UTC, giunatale commented on XXX_proposal_template.md
> +of 50govgen and a deposit of 5,000govgen.
```suggestion
of 50 $GOVGEN that will need to come from the initial onchain proposer, 
and a total deposit of 5,000 $GOVGEN that can be permissionlessly funded
by by any account with balance with arbitrary amounts.
```

2024-03-05 16:47 UTC, giunatale requested changes
sorry, previously approved by mistake, but thereis only a minor change request, the rest looks good TY!

2024-03-05 16:48 UTC, tbruyelle commented on XXX_proposal_template.md
> +of 50govgen and a deposit of 5,000govgen.
Can you update your suggestion plz? there's `by` repeated twice in the last line.

2024-03-05 18:52 UTC, giunatale commented on XXX_proposal_template.md
> +of 50govgen and a deposit of 5,000govgen.
done!

2024-03-05 22:15 UTC, giunatale approved these changes

2024-03-11 14:34 UTC, merged

2024-03-15 17:00 UTC, kristovatlas commented
LGTM